#!/bin/bash

if [ $# -ne 1 ]
    then
        echo "Run with 'activate' argument!"
        exit
    fi

GITREVS=`git rev-list --count HEAD`
GITHASH=`git rev-parse --short HEAD`
DATE=`date +"%Y-%m-%d %H:%M"`

cat > src/lib/cats/CATsMainHeaderConfig.hpp << EOF
#define LibBuildVersion_CATs         "2.${GITREVS}.${GITHASH}"
#define CATS_BUILDTIME       "${DATE}"
EOF

echo ""
echo "CATs Revision: 2.$GITREVS.$GITHASH ($DATE)"

